version: '2'
services:
  consul:
      image: "progrium/consul:latest"
      container_name: "consul"
      ports:
        - "8400:8400"
        - "8500:8500"
        - "8600:53"
      command: "-server -bootstrap -ui-dir /ui"
  app:
    container_name: "service1"
    depends_on:
      - "consul"
    build: .
    ports:
      - "8080:8080"
    network_mode: "host"